### ISSUE TITLE
PiT v23:  error in browser, blank screen when running project in pnpm

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-karaf-example#79]
When running demo with V23 using pnpm there is no view in browser just blank screen

How to reproduce
- clone the project
- bump vaadin version `mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.0.0.alpha3` 
- run `mvn -pl main-ui install -Prun -Dpnpm.enable=true`

**Comment by caalador** [comment]
I can see in the console
```
vaadin-bundle-59046e…fb3f6a.cache.js:946 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at Object.<anonymous> (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:946:880)
    at i (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:1:361)
    at Object.<anonymous> (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:946:1041)
    at i (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:1:361)
    at Object.<anonymous> (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:203:244)
    at i (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:1:361)
    at Object.<anonymous> (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:976:8536)
    at i (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:1:361)
    at Object.<anonymous> (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:3430:231)
    at i (http://localhost:8181/VAADIN/build/vaadin-bundle-59046e2….cache.js:1:361)
```

**Comment by joheriks** [comment]
No longer reproduces with `23.0.0.beta4`.

**Comment by manolo** [comment]
Couldn't reproduce either with beta4
